# Generated by Django 2.1 on 2020-05-28 15:27

from django.db import migrations, models
import posting.models


class Migration(migrations.Migration):

    dependencies = [
        ('posting', '0003_auto_20200521_1554'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=posting.models.date_upload_detection)),
            ],
            options={
                'db_table': 'upload',
                'managed': False,
            },
        ),
    ]
