# Generated by Django 2.1 on 2020-05-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserLikeHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_like_history',
                'managed': False,
            },
        ),
    ]
