# Generated by Django 2.1 on 2020-05-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_map', '0002_auto_20200428_1435'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
