# Generated by Django 3.0.3 on 2020-04-27 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserPick',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'db_table': 'user_pick',
                'managed': False,
            },
        ),
    ]
