# Generated by Django 3.0.3 on 2020-05-18 21:44

from django.db import migrations, models
import loginApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='image',
            field=models.ImageField(default='media/default/default.png', upload_to=loginApp.models.date_upload_profile),
        ),
        migrations.AlterField(
            model_name='user',
            name='age',
            field=models.DateField(blank=True, null=True),
        ),
    ]
