# Generated by Django 3.0.3 on 2020-05-18 22:21

from django.db import migrations, models
import loginApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0003_auto_20200518_2153'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_id',
            new_name='nickname',
        ),
        migrations.AlterField(
            model_name='user',
            name='image',
            field=models.ImageField(default='default/default.png', upload_to=loginApp.models.date_upload_profile),
        ),
    ]
