# Generated by Django 2.1 on 2020-05-28 15:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loginApp', '0004_auto_20200518_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
