# Generated by Django 3.0.3 on 2020-04-20 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PostingReviews',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('context', models.TextField(blank=True, null=True)),
                ('date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'posting_reviews',
                'managed': False,
            },
        ),
    ]
