# Generated by Django 2.1 on 2020-05-21 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('commentApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='postingreviews',
            options={'managed': False, 'ordering': ['date']},
        ),
    ]
