# Generated by Django 3.0.3 on 2020-04-12 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryImageM',
            fields=[
                ('ctgr_mid', models.AutoField(primary_key=True, serialize=False)),
                ('ctgr_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_image_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryImageS',
            fields=[
                ('ctgr_sid', models.AutoField(primary_key=True, serialize=False)),
                ('ctgr_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_image_s',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryL',
            fields=[
                ('ctgr_lid', models.AutoField(primary_key=True, serialize=False)),
                ('ctgr_name', models.CharField(max_length=45)),
            ],
            options={
                'db_table': 'category_l',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTextM',
            fields=[
                ('ctgr_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctgr_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category_text_m',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='CategoryTextS',
            fields=[
                ('ctgr_id', models.AutoField(primary_key=True, serialize=False)),
                ('ctgr_name', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'category_text_s',
                'managed': False,
            },
        ),
    ]
