# Generated by Django 3.0.3 on 2020-04-18 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserLScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_l_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_m_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserMScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_m_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserPlaceHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('place_id', models.CharField(blank=True, max_length=100, null=True)),
                ('context', models.TextField(blank=True, null=True)),
                ('img_cnt', models.IntegerField(blank=True, null=True)),
                ('like_cnt', models.IntegerField(blank=True, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('tag_1', models.CharField(blank=True, max_length=45, null=True)),
                ('tag_2', models.CharField(blank=True, max_length=45, null=True)),
                ('tag_3', models.CharField(blank=True, max_length=45, null=True)),
                ('tag_4', models.CharField(blank=True, max_length=45, null=True)),
                ('tag_5', models.CharField(blank=True, max_length=45, null=True)),
                ('tag_6', models.CharField(blank=True, max_length=45, null=True)),
            ],
            options={
                'db_table': 'user_place_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSHistory',
            fields=[
                ('idx', models.IntegerField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_s_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserSScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_s_score',
                'managed': False,
            },
        ),
    ]
