# Generated by Django 3.0.3 on 2020-04-20 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0002_userlscore_usermhistory_usermscore_userplacehistory_usershistory_usersscore'),
    ]

    operations = [
        migrations.CreateModel(
            name='ImageMHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_m_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageMScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_m_socre',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_s_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ImageSScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'image_s_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextMHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'text_m_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextMScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextSHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'text_s_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TextSScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'text_s_score',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='UserLHistory',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('cnt', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_l_history',
                'managed': False,
            },
        ),
        migrations.DeleteModel(
            name='UserMHistory',
        ),
        migrations.DeleteModel(
            name='UserSHistory',
        ),
        migrations.DeleteModel(
            name='UserSScore',
        ),
    ]
