# Generated by Django 3.0.3 on 2020-04-20 02:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0003_auto_20200420_0151'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSScore',
            fields=[
                ('idx', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'user_s_score',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='textmscore',
            table='text_m_score',
        ),
    ]
