# Generated by Django 3.0.3 on 2020-04-20 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0004_auto_20200420_0201'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserMScore',
        ),
        migrations.DeleteModel(
            name='UserSScore',
        ),
    ]
