# Generated by Django 3.0.3 on 2020-04-28 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0005_auto_20200420_1734'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='imagemscore',
            table='image_m_score',
        ),
    ]
