# Generated by Django 3.0.3 on 2020-05-19 02:14

from django.db import migrations, models
import recommendApp.models


class Migration(migrations.Migration):

    dependencies = [
        ('recommendApp', '0006_auto_20200428_1511'),
    ]

    operations = [
        migrations.CreateModel(
            name='Upload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=recommendApp.models.date_upload_recommend)),
            ],
            options={
                'db_table': 'upload',
            },
        ),
    ]
