# Generated by Django 2.1 on 2020-04-28 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('follow_feed', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={},
        ),
    ]
