# Generated by Django 3.0.4 on 2020-03-11 04:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recognition', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='subtitle',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title',
        ),
    ]
