# Generated by Django 2.1 on 2020-03-16 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('voice_recognition', '0004_auto_20200316_2321'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='post',
            table='voice_recognition_post',
        ),
    ]
